server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: 67089
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

Kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: AIzaSyB5C817hUNCHljhtpEh1G0TwXMrQdA3cas